// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    
    repositories {
        google()
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.2.0-alpha06'
        

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        google()
        jcenter()
    }
    //THIS IS WHAT YOU ARE ADDING
    project.ext {
        isRelease = false
        buildToolsVersion = "26.0.2" //String
        supportLibraryVersion = "27.0.0" //String
        sdp = "1.0.4" //String
        minSdkVersion = 19 //Integer
        targetSdkVersion = 26
        compileSdkVersion = 26
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
